In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [2]:
df = pd.read_csv("C:\\Users\\hp\\Desktop\\ITR2026\\ass 20\\ford_car_dataset.csv")

In [3]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,Fiesta,2017,12000,Automatic,15944,Petrol,150,57.7,1.0
1,Focus,2018,14000,Manual,9083,Petrol,150,57.7,1.0
2,Focus,2017,13000,Manual,12456,Petrol,150,57.7,1.0
3,Fiesta,2019,17500,Manual,10460,Petrol,145,40.3,1.5
4,Fiesta,2019,16500,Automatic,1482,Petrol,145,48.7,1.0
...,...,...,...,...,...,...,...,...,...
17961,B-MAX,2017,8999,Manual,16700,Petrol,150,47.1,1.4
17962,B-MAX,2014,7499,Manual,40700,Petrol,30,57.7,1.0
17963,Focus,2015,9999,Manual,7010,Diesel,20,67.3,1.6
17964,KA,2018,8299,Manual,5007,Petrol,145,57.7,1.2
17965,Focus,2015,8299,Manual,5007,Petrol,22,57.7,1.0

In [5]:
print(df.shape)

(17966, 9)

SyntaxError: invalid syntax (1998114957.py, line 1)

In [6]:
X = df.drop("price", axis=1)
Y = df["price"]
print("Shape of X :", X.shape)
print("Shape of Y :", Y.shape)

Shape of X : (17966, 8)
Shape of Y : (17966,)

In [7]:
cat_cols = X.select_dtypes(include=["object"]).columns
print(cat_cols)

X = pd.get_dummies(X, columns=cat_cols)

X = X.astype(int)

X.head()

Index(['model', 'transmission', 'fuelType'], dtype='str')

C:\Users\hp\AppData\Local\Temp\ipykernel_11996\2277647316.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include=["object"]).columns

,year,mileage,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,...,model_ Transit Tourneo,model_Focus,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2017,15944,150,57,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,2018,9083,150,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,2017,12456,150,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,2019,10460,145,40,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,2019,1482,145,48,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [5]:
x = df.copy()

NameError: name 'df' is not defined

In [4]:
num_cols = ["year", "mileage", "tax", "mpg", "engineSize"]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])
X.head()

NameError: name 'X' is not defined

In [2]:
import sys
print(sys.executable)
print(sys.version)

c:\Users\hp\AppData\Local\Programs\Python\Python314\python.exe
3.14.5 (tags/v3.14.5:5607950, May 10 2026, 10:43:50) [MSC v.1944 64 bit (AMD64)]

In [ ]:
 = df.copy()

from sklearn.preprocessing import StandardScaler

num_cols = ["year", "mileage", "tax", "mpg", "engineSize"]

scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

X.head()X

NameError: name 'df' is not defined

In [15]:
df = pd.read_csv("C:\\Users\\hp\\Desktop\\ITR2026\\ass 20\\ford_car_dataset.csv")

In [16]:
x = df.copy()

In [17]:
X = df.copy()

from sklearn.preprocessing import StandardScaler

num_cols = ["year", "mileage", "tax", "mpg", "engineSize"]

scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

X.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,Fiesta,0.065128,12000,Automatic,-0.380998,Petrol,0.591358,-0.020442,-0.811386
1,Focus,0.552866,14000,Manual,-0.733359,Petrol,0.591358,-0.020442,-0.811386
2,Focus,0.065128,13000,Manual,-0.560132,Petrol,0.591358,-0.020442,-0.811386
3,Fiesta,1.040605,17500,Manual,-0.662640,Petrol,0.510727,-1.738890,0.345070
4,Fiesta,1.040605,16500,Automatic,-1.123724,Petrol,0.510727,-0.909294,-0.811386

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y,
    test_size=0.33,
    random_state=42
)

print("X_train Shape :", X_train.shape)
print("X_test Shape  :", X_test.shape)
print("y_train Shape :", y_train.shape)
print("y_test Shape  :", y_test.shape)

NameError: name 'Y' is not defined

In [19]:
# Target
y = df["price"]

# Features
X = df.drop("price", axis=1)

In [20]:
X = pd.get_dummies(X, drop_first=True)

In [21]:
from sklearn.preprocessing import StandardScaler

num_cols = ["year", "mileage", "tax", "mpg", "engineSize"]

scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

In [23]:
print(y)

0        12000
1        14000
2        13000
3        17500
4        16500
         ...
17961     8999
17962     7499
17963     9999
17964     8299
17965     8299
Name: price, Length: 17966, dtype: int64

In [27]:
train_test_split( X, y,)

[           year   mileage       tax       mpg  engineSize  model_ C-MAX  \
 16439 -2.373565  0.420121 -1.505053  0.927668    0.576362         False
 17468 -3.836780  4.654872  3.010294 -2.183316    1.501527         False
 17887  0.552866 -0.583550  0.510727  0.769650   -0.811386         False
 3987   0.552866 -0.378995  0.510727  0.927668    0.345070         False
 13099  1.040605 -0.691452  0.510727 -1.847527    0.345070         False
 ...         ...       ...       ...       ...         ...           ...
 17916  1.040605 -1.117664  0.510727 -0.909294   -0.811386         False
 9638   1.528343 -1.198962  0.510727  0.769650    1.501527         False
 4576   0.065128 -0.932008  0.188202 -0.356230   -0.348804         False
 14658  0.065128  0.106586 -1.827578  0.769650   -0.811386         False
 8260   1.040605 -0.663154  0.510727 -2.588238    1.501527         False

        model_ EcoSport  model_ Edge  model_ Escort  model_ Fiesta  ...  \
 16439            False        False          False          False  ...
 17468            False        False          False          False  ...
 17887            False        False          False           True  ...
 3987             False        False          False          False  ...
 13099            False        False          False          False  ...
 ...                ...          ...            ...            ...  ...
 17916            False        False          False           True  ...
 9638             False        False          False          False  ...
 4576             False        False          False           True  ...
 14658            False        False          False           True  ...
 8260             False        False          False          False  ...

        model_ Tourneo Connect  model_ Tourneo Custom  model_ Transit Tourneo  \
 16439                   False                  False                   False
 17468                   False                  False                   False
 17887                   False                  False                   False
 3987                    False                  False                   False
 13099                   False                  False                   False
 ...                       ...                    ...                     ...
 17916                   False                  False                   False
 9638                    False                  False                   False
 4576                    False                  False                   False
 14658                   False                  False                   False
 8260                    False                   True                   False

        model_Focus  transmission_Manual  transmission_Semi-Auto  \
 16439        False                 True                   False
 17468        False                 True                   False
 17887        False                 True                   False
 3987         False                False                    True
 13099        False                 True                   False
 ...            ...                  ...                     ...
 17916        False                False                   False
 9638         False                 True                   False
 4576         False                 True                   False
 14658        False                 True                   False
 8260         False                 True                   False

        fuelType_Electric  fuelType_Hybrid  fuelType_Other  fuelType_Petrol
 16439              False            False           False            False
 17468              False            False           False             True
 17887              False            False           False             True
 3987               False            False           False            False
 13099              False            False           False             True
 ...                  ...              ...             ...              ...
 17916              False            False           False             True
 9638               False            False           False            False
 4576               False            False           False             True
 14658              False            False           False             True
 8260               False            False           False            False

 [13474 rows x 34 columns],
            year   mileage       tax       mpg  engineSize  model_ C-MAX  \
 6426   0.065128 -0.169458  0.510727 -0.553753   -0.811386         False
 4970   1.040605 -0.914547  0.510727 -0.454992   -0.811386         False
 1923   0.552866 -0.457263  0.591358 -0.988303   -0.348804         False
 7084  -0.910349  1.742463 -1.827578  1.618998    0.345070         False
 11622  0.552866  0.091230  0.510727 -0.138955   -0.811386         False
 ...         ...       ...       ...       ...         ...           ...
 11196  1.040605 -1.167224  0.510727 -0.988303   -0.348804         False
 14305  0.065128 -0.021909  0.510727  0.216586   -0.811386         False
 9327   0.552866 -0.016055  0.510727 -0.138955   -0.811386         False
 7871   0.552866 -0.084565  0.510727  0.769650   -0.811386         False
 10081  0.552866 -0.751283  0.510727  0.344976   -0.811386         False

        model_ EcoSport  model_ Edge  model_ Escort  model_ Fiesta  ...  \
 6426              True        False          False          False  ...
 4970              True        False          False          False  ...
 1923             False        False          False          False  ...
 7084             False        False          False          False  ...
 11622            False        False          False           True  ...
 ...                ...          ...            ...            ...  ...
 11196            False        False          False          False  ...
 14305            False        False          False          False  ...
 9327             False        False          False           True  ...
 7871             False        False          False           True  ...
 10081            False        False          False          False  ...

        model_ Tourneo Connect  model_ Tourneo Custom  model_ Transit Tourneo  \
 6426                    False                  False                   False
 4970                    False                  False                   False
 1923                    False                  False                   False
 7084                    False                  False                   False
 11622                   False                  False                   False
 ...                       ...                    ...                     ...
 11196                   False                  False                   False
 14305                   False                  False                   False
 9327                    False                  False                   False
 7871                    False                  False                   False
 10081                   False                  False                   False

        model_Focus  transmission_Manual  transmission_Semi-Auto  \
 6426         False                 True                   False
 4970         False                 True                   False
 1923         False                 True                   False
 7084         False                 True                   False
 11622        False                 True                   False
 ...            ...                  ...                     ...
 11196        False                 True                   False
 14305        False                 True                   False
 9327         False                 True                   False
 7871         False                 True                   False
 10081        False                 True                   False

        fuelType_Electric  fuelType_Hybrid  fuelType_Other  fuelType_Petrol
 6426               False            False           False             True
 4970               False            False           False             True
 1923               False            False           False             True
 7084               False            False           False            False
 11622              False            False           False             True
 ...                  ...              ...             ...              ...
 11196              False            False           False             True
 14305              False            False           False             True
 9327               False            False           False             True
 7871               False            False           False             True
 10081              False            False           False             True

 [4492 rows x 34 columns],
 16439     6195
 17468     2790
 17887    10850
 3987     14000
 13099    18800
          ...
 17916    16660
 9638     21000
 4576      8498
 14658     9360
 8260     29500
 Name: price, Length: 13474, dtype: int64,
 6426      9280
 4970     15000
 1923      7995
 7084      7991
 11622    10699
          ...
 11196    11880
 14305    10752
 9327     10600
 7871     11387
 10081    12195
 Name: price, Length: 4492, dtype: int64]

In [30]:
from sklearn.model_selection import train_test_split

X = df.drop("price", axis=1)
y = df["price"]

# Categorical columns ko encode karo
X = pd.get_dummies(X, drop_first=True)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [35]:
train_test_split(X, y, )

[       year  mileage  tax   mpg  engineSize  model_ C-MAX  model_ EcoSport  \
 6594   2016    12376   20  60.1         1.0         False            False
 3359   2017    38000    0  65.7         1.0         False            False
 16445  2015    80000    0  74.3         1.5         False            False
 15214  2017     6706  145  64.2         1.5         False            False
 8185   2017    47267  145  74.3         1.5         False            False
 ...     ...      ...  ...   ...         ...           ...              ...
 6852   2019     2450  145  51.4         1.0         False            False
 9419   2018    17139  150  57.7         1.0         False            False
 17573  2017    32882  125  51.4         2.0         False            False
 10249  2018     3469  145  51.4         1.0         False             True
 16473  2018     9000  145  54.3         0.0         False             True

        model_ Edge  model_ Escort  model_ Fiesta  ...  model_ Tourneo Connect  \
 6594         False          False          False  ...                   False
 3359         False          False           True  ...                   False
 16445        False          False          False  ...                   False
 15214        False          False          False  ...                   False
 8185         False          False          False  ...                   False
 ...            ...            ...            ...  ...                     ...
 6852         False          False          False  ...                   False
 9419         False          False          False  ...                   False
 17573        False          False          False  ...                   False
 10249        False          False          False  ...                   False
 16473        False          False          False  ...                   False

        model_ Tourneo Custom  model_ Transit Tourneo  model_Focus  \
 6594                   False                   False        False
 3359                   False                   False        False
 16445                  False                   False        False
 15214                  False                   False        False
 8185                   False                   False        False
 ...                      ...                     ...          ...
 6852                   False                   False        False
 9419                   False                   False        False
 17573                  False                   False        False
 10249                  False                   False        False
 16473                  False                   False        False

        transmission_Manual  transmission_Semi-Auto  fuelType_Electric  \
 6594                  True                   False              False
 3359                  True                   False              False
 16445                 True                   False              False
 15214                 True                   False              False
 8185                  True                   False              False
 ...                    ...                     ...                ...
 6852                 False                   False              False
 9419                  True                   False              False
 17573                 True                   False              False
 10249                 True                   False              False
 16473                 True                   False              False

        fuelType_Hybrid  fuelType_Other  fuelType_Petrol
 6594             False           False             True
 3359             False           False             True
 16445            False           False            False
 15214            False           False            False
 8185             False           False            False
 ...                ...             ...              ...
 6852             False           False             True
 9419             False           False             True
 17573            False           False            False
 10249            False           False             True
 16473            False           False             True

 [13474 rows x 34 columns],
        year  mileage  tax   mpg  engineSize  model_ C-MAX  model_ EcoSport  \
 14889  2017    29358    0  65.7         1.0         False            False
 12777  2020      800  145  60.1         1.0         False            False
 12236  2019    20893  150  60.1         1.0         False            False
 2510   2013    70048    0  65.7         1.0         False            False
 8661   2017    12890  145  65.7         1.0         False            False
 ...     ...      ...  ...   ...         ...           ...              ...
 12230  2018     5500  150  55.4         1.1         False            False
 15671  2017    18291    0  74.3         1.5         False            False
 15989  2016    18543  125  54.3         1.2         False            False
 6924   2018    11097  145  62.8         1.0         False            False
 11657  2019     5013  145  60.1         1.0         False            False

        model_ Edge  model_ Escort  model_ Fiesta  ...  model_ Tourneo Connect  \
 14889        False          False           True  ...                   False
 12777        False          False           True  ...                   False
 12236        False          False          False  ...                   False
 2510         False          False           True  ...                   False
 8661         False          False           True  ...                   False
 ...            ...            ...            ...  ...                     ...
 12230        False          False           True  ...                   False
 15671        False          False          False  ...                   False
 15989        False          False           True  ...                   False
 6924         False          False           True  ...                   False
 11657        False          False          False  ...                   False

        model_ Tourneo Custom  model_ Transit Tourneo  model_Focus  \
 14889                  False                   False        False
 12777                  False                   False        False
 12236                  False                   False        False
 2510                   False                   False        False
 8661                   False                   False        False
 ...                      ...                     ...          ...
 12230                  False                   False        False
 15671                  False                   False        False
 15989                  False                   False        False
 6924                   False                   False        False
 11657                  False                   False        False

        transmission_Manual  transmission_Semi-Auto  fuelType_Electric  \
 14889                 True                   False              False
 12777                 True                   False              False
 12236                 True                   False              False
 2510                  True                   False              False
 8661                  True                   False              False
 ...                    ...                     ...                ...
 12230                 True                   False              False
 15671                 True                   False              False
 15989                 True                   False              False
 6924                  True                   False              False
 11657                 True                   False              False

        fuelType_Hybrid  fuelType_Other  fuelType_Petrol
 14889            False           False             True
 12777            False           False             True
 12236            False           False             True
 2510             False           False             True
 8661             False           False             True
 ...                ...             ...              ...
 12230            False           False             True
 15671            False           False            False
 15989            False           False             True
 6924             False           False             True
 11657            False           False             True

 [4492 rows x 34 columns],
 6594     10080
 3359      8955
 16445     6475
 15214    15489
 8185      9860
          ...
 6852     16107
 9419     12295
 17573    17000
 10249    16333
 16473    12867
 Name: price, Length: 13474, dtype: int64,
 14889    10600
 12777    18499
 12236    14400
 2510      5698
 8661     10901
          ...
 12230    10500
 15671     9725
 15989     8277
 6924     13295
 11657    17299
 Name: price, Length: 4492, dtype: int64]

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y,
    test_size=0.33,
    random_state=42
)

print("X_train Shape :", X_train.shape)
print("X_test Shape  :", X_test.shape)
print("y_train Shape :", y_train.shape)
print("y_test Shape  :", y_test.shape)

NameError: name 'Y' is not defined

In [36]:
y = df["price"]

In [37]:
X = df.drop("price", axis=1)
X = pd.get_dummies(X, drop_first=True)

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(12037, 34)
(5929, 34)
(12037,)
(5929,)

In [39]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
print("Intercept :", model.intercept_)
print("Coefficients :")
print(model.coef_)

Intercept : -2074107.0100380576
Coefficients :
[ 1.03519019e+03 -6.88172479e-02 -8.72837078e-01 -8.11959580e+01
  2.49604817e+03  1.02256674e+03  1.59582894e+03  9.48932634e+03
 -2.86893345e+02  1.11009434e+03  3.16094123e+03  3.52042413e+03
  6.51975319e+03  1.42401376e+03  4.00118740e+03 -3.21569856e+02
 -2.91834532e+03  3.66835970e+03  2.93011945e+03  1.21854169e+04
  7.67831356e+03  9.09494702e-13  6.32532534e+03  1.81898940e-12
  3.44637248e+03  6.64766338e+03 -4.19048723e+02 -3.22112575e+02
 -4.19837381e+02 -1.30858400e+02 -1.69406589e-21  8.17669896e+03
 -1.38380971e+01 -4.21242665e+02]

In [41]:
y_pred = model.predict(X_test)

print("First 10 Predictions:")
print(y_pred[:10])

print("First 10 Actual Values:")
print(y_test.iloc[:10].values)

First 10 Predictions:
[ 6696.79284496  9174.09561232  9877.805433    3899.75677174
  3027.88376555 16621.7658302  27589.46586814 12114.54854698
 11586.4953738  16776.36520711]
First 10 Actual Values:
[ 6995  8999  7998  5491  3790 18200 22998 11000  7600 14985]

In [42]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R² Score :", r2)

R² Score : 0.840229131999295

In [43]:
import joblib
joblib.dump(model, "LR_ford_car.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")
print("Model Saved Successfully!")

Model Saved Successfully!